AWSTemplateFormatVersion: '2010-09-09'
Description: Thumbnail generator pipeline
Resources:
  S3SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: storicard-images-upload
  S3ProcessedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: storicard-thumbnails-save
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: lambda-s3-access
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !GetAtt S3SourceBucket.Arn
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !GetAtt S3ProcessedBucket.Arn
  ProcessImageLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: thumbnail-test-lambda
        S3Key: lambdaHandler.zip
      Handler: lambda_handler.lambda_handler
      Runtime: python3.8
      Role: !GetAtt LambdaRole.Arn
      Layers:
        - arn:aws:lambda:us-east-1:905418138662:layer:ThumbnailLayer:2
  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ProcessImageLambda.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt S3SourceBucket.Arn
Outputs:
  SourceBucketArn:
    Description: ARN of SourceBucket
    Value: !GetAtt S3SourceBucket.Arn
  ProcessedBucketArn:
    Description: ARN of ProcessedBucket
    Value: !GetAtt S3ProcessedBucket.Arn
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt ProcessImageLambda.Arn