AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Thumbnail generator pipeline
Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: upload-images
  ProcessedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: save-thumbnails
  LambdaFunctionZip:
    Type: AWS::S3::Object
    Properties:
      Bucket: thumbnail-test-lambda
      Key: lambdaHandler.zip
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
              - lambda:GetLayerVersion
      ManagedPolicyArns:
        - - ARN::aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  ProcessImageLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ThumbnailGenerator
      Runtime: python3.8
      Handler: lambda_handler.lambda_handler
      CodeUri:
        Bucket: thumbnail-test-lambda
        Key: lambdaHandler.zip
      Layers: arn:aws:lambda:us-east-1:905418138662:layer:ThumbnailLayer:1
      Events:
        SourceBucket:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucket
            Events:
              - s3:ObjectCreated:*
              - s3:ObjectRemoved:*
      Environment:
        Variables:
          PROCESSEDBUCKET_BUCKET_NAME: !Ref ProcessedBucket
          PROCESSEDBUCKET_BUCKET_ARN: !GetAtt ProcessedBucket.Arn
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:GetObjectAcl
                - s3:GetObjectLegalHold
                - s3:GetObjectRetention
                - s3:GetObjectTorrent
                - s3:GetObjectVersion
                - s3:GetObjectVersionAcl
                - s3:GetObjectVersionForReplication
                - s3:GetObjectVersionTorrent
                - s3:ListBucket
                - s3:ListBucketMultipartUploads
                - s3:ListBucketVersions
                - s3:ListMultipartUploadParts
                - s3:AbortMultipartUpload
                - s3:DeleteObject
                - s3:DeleteObjectVersion
                - s3:PutObject
                - s3:PutObjectLegalHold
                - s3:PutObjectRetention
                - s3:RestoreObject
              Resource:
                - !Sub arn:${AWS::Partition}:s3:::${ProcessedBucket}
                - !Sub arn:${AWS::Partition}:s3:::${ProcessedBucket}/*
  LambdaS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LambdaS3AccessPolicy
      Roles: LambdaRole
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource:
              - arn:aws:s3:::${upload-images}
              - arn:aws:s3:::save-thumbnails${AWS::StackName}/*
  EventSourceMapping:
    Type: AWS::Serverless::EventSourceMapping
    Properties:
      FunctionName: ThumbnailGenerator
      EventSourceArn: arn:aws:s3:::upload-images:ObjectCreated:*